make_a_shake/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('user_details/', user_views.user_details, name='user_details'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
#url patterns for shop pages
urlpatterns = [
    path('', views.home, name='shop-home'),
    path('ice_cream/', views.ice_cream, name='shop-ice_cream'),
    path('order_details/', views.order_details, name='shop-order_details'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User



#create models for database tables here

class Ice_cream(models.Model):
    name = models.CharField(max_length = 100, unique=True)
    cost = models.FloatField(null=True, blank=True, default=None)
    def __str__(self):
        return self.name 

class Flavour(models.Model):
    name = models.CharField(max_length = 100, unique=True)
    cost = models.FloatField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name 

class Topping(models.Model):
    name = models.CharField(max_length = 100, unique=True)
    cost = models.FloatField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name 

class Milk_shake(models.Model):
    m_ice_cream = models.ForeignKey(Ice_cream,to_field='name',on_delete=None, default='none')
    m_flavour = models.ForeignKey(Flavour,to_field='name',on_delete=None, default='none')
    m_topping = models.ForeignKey(Topping,to_field='name',on_delete=None, default='none')
    m_cost = models.FloatField(null=True, blank=True, default=None) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
# Create your models here.

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields

#edited for registration form
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()


    class Meta:# gives nested name space and keeps configs in one space
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

shop/views.py
from django.shortcuts import redirect, render

from .models import Flavour, Ice_cream, Topping, Milk_shake
from django.contrib.auth.models import User
import logging


def home(request):
    
    return render(request, 'shop/home.html')
    
#views for each webpage - data from database is passed into here and then to the front end.
#logic goes here,
def ice_cream(request):
    logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.INFO)
    logging.info("choices made")


    if 'cice' and 'cflav' and 'ctop' in request.GET:
        
        
        cice = request.GET.getlist('cice')
        cflav = request.GET.getlist('cflav')
        ctop = request.GET.getlist('ctop')
        milk = [cice, cflav,ctop]
        request.session['x'] = milk
        return redirect('shop:shop-order_details' )

        
        
    

    context_i={
        'ice_creams' : Ice_cream.objects.all(),
        'flavours' : Flavour.objects.all(),
        'toppings' : Topping.objects.all()
        }
   
    
    return render(request, 'shop/ice_cream.html',context_i)




# created milkshakes are saved to data base
def order_details(request):
    
    milk = request.session['x']
    ice = str(milk[0])
    flav = str(milk[1])
    top = str(milk[2])
    ice2 = ice[2:len(ice)-2]
    flav2 = flav[2:len(flav)-2]
    top2 =top[2:len(top)-2]

    ice_v = Ice_cream.objects.get(name=ice2)
    ice_cost = ice_v.cost
    flav_v = Flavour.objects.get(name=flav2)
    flav_cost = flav_v.cost
    top_v = Topping.objects.get(name=top2)
    top_cost = top_v.cost

    total_cost = ice_cost + flav_cost + top_cost
    currentu = request.user

    m = Milk_shake(m_ice_cream = ice_v, m_flavour = flav_v, m_topping = top_v, m_cost = total_cost, user = currentu)
   

    context_m={
        'milk_shakes' : Milk_shake.objects.all(),
        'cice' : ice2,
        'cflav' :flav2,
        'ctop' : top2,
        'tot' : total_cost
    }

    if request.method == 'POST':
        m.save()
        return redirect('shop:shop-home') 

    return render(request, 'shop/order_details.html', context_m)
# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
#user views for registration form
def register(request):
    
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()# auto matically hashes passwords for the account
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account has been created, please log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required #decorator adds functionality to profile view, users has to be logged in
def user_details(request):
    return render(request, 'users/user_details.html')

# Create your views here.

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<!--this is the base html for back ground and nav bar-->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'shop/main.css' %}">

    {% if title %}
        <title>Django shop - {{ title }}</title>
    {% else %}
        <title>Django shop
        </title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'shop:shop-home' %}">Make a shake</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'shop:shop-home' %}">Home</a>
              
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav"><!--if statement to check is user is logged in or out-->
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'user_details' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <!--<h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>-->
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/home.html
{% extends "shop/base.html" %}
{% block content %}

    <div class="content-section">
        <h1>Make a Shake</h1>
        <button type="button">
            <a href="{% url 'shop:shop-ice_cream' %}">start order</a>
        </button>

      
    </div>

{% endblock content %}

shop/templates/shop/ice_cream.html
{% extends "shop/base.html" %}
{% block content %}
    <div class="content-section">
        <div>
            <form method="get" > {%csrf_token%}
                <h2>Pick your ice-cream</h2>
                <select name = "cice">
                    <option selected disabled="true">--Ice cream--</option>
                    {% for result in ice_creams %}
                    <option>{{ result.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <h2>Pick your flavour</h2>
                <select name = "cflav">
                    <option selected disabled="true">--Flavour--</option>
                    {% for result in flavours %}
                    <option>{{ result.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <h2>Pick your topping</h2>
                <select name = "ctop">
                    <option selected disabled="true">--Toppings--</option>
                    {% for result in toppings %}
                    <option>{{ result.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <input type = "submit" value="Submit">
        </form>

    </div>
    <!--<div>
        <h2>total cost:</h2>
        <h3>{{ totcost }}</h3>
    </div>-->

{% endblock content %}

shop/templates/shop/order_details.html
{% extends "shop/base.html" %}
{% block content %}

    <div class="content-section">
        <h1>order details</h1>
        <h2>Ice-cream: {{cice}}</h2>
        <h2>Flavour: {{cflav}}</h2>
        <h2>Topping: {{ctop}}</h2>

        <h3>Total cost  £{{tot}}</h3>
        

      
    </div>
    <div>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Confirm">
        </form>
    </div>

{% endblock content %}

users/templates/users/login.html
{% extends "shop/base.html" %}
{% block content %}
    <div> 
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}

                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="content-section"> <!-- need to make universal html template-->
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend> 
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Need an account? <a class="ml-2" href="{% url 'register' %}">Sign up here</a></small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "shop/base.html" %}
{% block content %}

    <div> 
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}

                </div>
            {% endfor %}
        {% endif %}
    </div>
    <h2>Logout successful</h2>
    
       
        <div class="border-top pt-3">
            <small class="text-muted"><a  href="{% url 'login' %}">Login</a></small>
        </div>
    
{% endblock content %}

users/templates/users/register.html
{% extends "shop/base.html" %}
{% block content %}
    <div> 
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}

                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="content-section"> 
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join</legend> 
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Already got an account? <a class="ml-2" href="{% url 'login' %}">Login</a></small>
        </div>
    </div>
{% endblock content %}

users/templates/users/user_details.html
{% extends "shop/base.html" %}
{% block content %}
    <h1><!--user details-->
        Your details:
    </h1>
    <h2>Username: {{ user.username }}</h2>
    <h2>Name: {{user.first_name}}, {{user.last_name}}</h2>
    <h2>Email: {{user.email}}</h2>
    
{% endblock content %}